[package]
name = "surechigai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
ble-peripheral-rust = "0.2"
btleplug = "0.13"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
futures = "0.3"
